spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_account?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  redis:
    host: 106.12.84.126
    port: 6379
server:
  port: 9084
logging:
  level:
    - io.seata: debug
    - org.springframework.cloud.alibaba.seata.web: debug
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9091/eureka