spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://192.168.150.131:3306/db_account?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
server:
  port: 9094
logging:
  level:
    - io.seata: debug
    - org.springframework.cloud.alibaba.seata.web: debug
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9091/eureka