spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_storage?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
server:
  port: 9093
logging:
  level:
    - io.seata: debug
    - org.springframework.cloud.alibaba.seata.web: debug